// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcdemoproto.proto

package rpcdemoproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppendEntriesRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId             uint64   `protobuf:"varint,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	Log                  []string `protobuf:"bytes,3,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesRequest) Reset()         { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()    {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcdemoproto_4636cbd0c631c5d4, []int{0}
}
func (m *AppendEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRequest.Unmarshal(m, b)
}
func (m *AppendEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRequest.Marshal(b, m, deterministic)
}
func (dst *AppendEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRequest.Merge(dst, src)
}
func (m *AppendEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRequest.Size(m)
}
func (m *AppendEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRequest proto.InternalMessageInfo

func (m *AppendEntriesRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderId() uint64 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AppendEntriesRequest) GetLog() []string {
	if m != nil {
		return m.Log
	}
	return nil
}

type AppendEntriesResponse struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResponse) Reset()         { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()    {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcdemoproto_4636cbd0c631c5d4, []int{1}
}
func (m *AppendEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResponse.Unmarshal(m, b)
}
func (m *AppendEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResponse.Marshal(b, m, deterministic)
}
func (dst *AppendEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResponse.Merge(dst, src)
}
func (m *AppendEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResponse.Size(m)
}
func (m *AppendEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResponse proto.InternalMessageInfo

func (m *AppendEntriesResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type VoteRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId          uint64   `protobuf:"varint,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteRequest) Reset()         { *m = VoteRequest{} }
func (m *VoteRequest) String() string { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()    {}
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcdemoproto_4636cbd0c631c5d4, []int{2}
}
func (m *VoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRequest.Unmarshal(m, b)
}
func (m *VoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRequest.Marshal(b, m, deterministic)
}
func (dst *VoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRequest.Merge(dst, src)
}
func (m *VoteRequest) XXX_Size() int {
	return xxx_messageInfo_VoteRequest.Size(m)
}
func (m *VoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRequest proto.InternalMessageInfo

func (m *VoteRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteRequest) GetCandidateId() uint64 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

type VoteResponse struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteResponse) Reset()         { *m = VoteResponse{} }
func (m *VoteResponse) String() string { return proto.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()    {}
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcdemoproto_4636cbd0c631c5d4, []int{3}
}
func (m *VoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteResponse.Unmarshal(m, b)
}
func (m *VoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteResponse.Marshal(b, m, deterministic)
}
func (dst *VoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteResponse.Merge(dst, src)
}
func (m *VoteResponse) XXX_Size() int {
	return xxx_messageInfo_VoteResponse.Size(m)
}
func (m *VoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoteResponse proto.InternalMessageInfo

func (m *VoteResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

func init() {
	proto.RegisterType((*AppendEntriesRequest)(nil), "rpcdemoproto.AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesResponse)(nil), "rpcdemoproto.AppendEntriesResponse")
	proto.RegisterType((*VoteRequest)(nil), "rpcdemoproto.VoteRequest")
	proto.RegisterType((*VoteResponse)(nil), "rpcdemoproto.VoteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HeartBeatServiceClient is the client API for HeartBeatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HeartBeatServiceClient interface {
	KeepHearBeat(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
}

type heartBeatServiceClient struct {
	cc *grpc.ClientConn
}

func NewHeartBeatServiceClient(cc *grpc.ClientConn) HeartBeatServiceClient {
	return &heartBeatServiceClient{cc}
}

func (c *heartBeatServiceClient) KeepHearBeat(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, "/rpcdemoproto.HeartBeatService/KeepHearBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeartBeatServiceServer is the server API for HeartBeatService service.
type HeartBeatServiceServer interface {
	KeepHearBeat(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
}

func RegisterHeartBeatServiceServer(s *grpc.Server, srv HeartBeatServiceServer) {
	s.RegisterService(&_HeartBeatService_serviceDesc, srv)
}

func _HeartBeatService_KeepHearBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartBeatServiceServer).KeepHearBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcdemoproto.HeartBeatService/KeepHearBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartBeatServiceServer).KeepHearBeat(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HeartBeatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcdemoproto.HeartBeatService",
	HandlerType: (*HeartBeatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeepHearBeat",
			Handler:    _HeartBeatService_KeepHearBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcdemoproto.proto",
}

// AppendEntriesServiceClient is the client API for AppendEntriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppendEntriesServiceClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
}

type appendEntriesServiceClient struct {
	cc *grpc.ClientConn
}

func NewAppendEntriesServiceClient(cc *grpc.ClientConn) AppendEntriesServiceClient {
	return &appendEntriesServiceClient{cc}
}

func (c *appendEntriesServiceClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, "/rpcdemoproto.AppendEntriesService/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppendEntriesServiceServer is the server API for AppendEntriesService service.
type AppendEntriesServiceServer interface {
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
}

func RegisterAppendEntriesServiceServer(s *grpc.Server, srv AppendEntriesServiceServer) {
	s.RegisterService(&_AppendEntriesService_serviceDesc, srv)
}

func _AppendEntriesService_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppendEntriesServiceServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcdemoproto.AppendEntriesService/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppendEntriesServiceServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppendEntriesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcdemoproto.AppendEntriesService",
	HandlerType: (*AppendEntriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _AppendEntriesService_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcdemoproto.proto",
}

// VoteServiceClient is the client API for VoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VoteServiceClient interface {
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
}

type voteServiceClient struct {
	cc *grpc.ClientConn
}

func NewVoteServiceClient(cc *grpc.ClientConn) VoteServiceClient {
	return &voteServiceClient{cc}
}

func (c *voteServiceClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, "/rpcdemoproto.VoteService/Vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoteServiceServer is the server API for VoteService service.
type VoteServiceServer interface {
	Vote(context.Context, *VoteRequest) (*VoteResponse, error)
}

func RegisterVoteServiceServer(s *grpc.Server, srv VoteServiceServer) {
	s.RegisterService(&_VoteService_serviceDesc, srv)
}

func _VoteService_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcdemoproto.VoteService/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcdemoproto.VoteService",
	HandlerType: (*VoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Vote",
			Handler:    _VoteService_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcdemoproto.proto",
}

func init() { proto.RegisterFile("rpcdemoproto.proto", fileDescriptor_rpcdemoproto_4636cbd0c631c5d4) }

var fileDescriptor_rpcdemoproto_4636cbd0c631c5d4 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xa9, 0x0d, 0x5a, 0x27, 0x11, 0xca, 0xa2, 0x10, 0x73, 0x0a, 0xf1, 0xd2, 0x53, 0x0f,
	0xf5, 0xec, 0xc1, 0x3f, 0x45, 0x45, 0x4f, 0x11, 0xb4, 0xd7, 0x35, 0xfb, 0x90, 0x60, 0x9b, 0x5d,
	0x77, 0xa7, 0xfd, 0xfc, 0x92, 0xc4, 0x94, 0xa4, 0x84, 0x9c, 0xbc, 0x2c, 0x33, 0xbf, 0xdd, 0x7d,
	0xf3, 0x78, 0x43, 0xc2, 0x9a, 0x4c, 0x61, 0xa3, 0x8d, 0xd5, 0xac, 0xe7, 0xd5, 0x29, 0x82, 0x36,
	0x4b, 0x56, 0x74, 0x7e, 0x6b, 0x0c, 0x0a, 0xb5, 0x2c, 0xd8, 0xe6, 0x70, 0x29, 0x7e, 0xb6, 0x70,
	0x2c, 0x04, 0x79, 0x0c, 0xbb, 0x09, 0x47, 0xf1, 0x68, 0xe6, 0xa5, 0x55, 0x2d, 0x22, 0x9a, 0xac,
	0x21, 0x15, 0xec, 0xb3, 0x0a, 0x8f, 0x2a, 0xbe, 0xef, 0xc5, 0x94, 0xc6, 0x6b, 0xfd, 0x15, 0x8e,
	0xe3, 0xf1, 0xec, 0x34, 0x2d, 0xcb, 0x64, 0x49, 0x17, 0x07, 0xca, 0xce, 0xe8, 0xc2, 0xa1, 0x57,
	0x3a, 0xa4, 0x13, 0xb7, 0xcd, 0x32, 0x38, 0x57, 0x29, 0x4f, 0xd2, 0xa6, 0x4d, 0xee, 0xc9, 0x7f,
	0xd7, 0x8c, 0x21, 0x5f, 0x31, 0xf9, 0x99, 0x2c, 0x54, 0xae, 0x24, 0x63, 0x6f, 0xad, 0x8d, 0x92,
	0x07, 0x0a, 0x6a, 0x91, 0x01, 0x0b, 0x31, 0xf9, 0x3b, 0xcd, 0x78, 0xb4, 0xb2, 0x60, 0xa8, 0x3f,
	0x1b, 0x6d, 0xb4, 0xf8, 0xa6, 0xe9, 0x13, 0xa4, 0xe5, 0x3b, 0x48, 0x7e, 0x83, 0xdd, 0xe5, 0x19,
	0xc4, 0x07, 0x05, 0x2f, 0x80, 0x29, 0x79, 0x89, 0x45, 0x32, 0xef, 0x44, 0xde, 0x97, 0x6d, 0x74,
	0x35, 0xf8, 0xa6, 0xb6, 0xb8, 0x30, 0x07, 0x8b, 0x69, 0x06, 0xae, 0xe8, 0xac, 0xc3, 0xff, 0x6f,
	0xe2, 0x6b, 0x9d, 0x74, 0x33, 0xe8, 0x86, 0xbc, 0xb2, 0x15, 0x97, 0xdd, 0xbf, 0xad, 0x65, 0x44,
	0x51, 0xdf, 0x55, 0xad, 0xf6, 0x79, 0x5c, 0xb1, 0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3,
	0xc5, 0x5b, 0x7e, 0x83, 0x02, 0x00, 0x00,
}
